---

- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  vars:
    k3s_version: v0.3.0
    ansible_user: vagrant
    systemd_dir: /lib/systemd/system
    master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
  roles:
    - { role: download }


- hosts: master
  gather_facts: yes
  become: yes
  vars:
    k3s_version: v0.3.0
    ansible_user: vagrant
    systemd_dir: /lib/systemd/system
    master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
  roles:
    - { role: k3s/master }

- hosts: node
  gather_facts: yes
  become: yes
  vars:
    k3s_version: v0.3.0
    ansible_user: vagrant
    systemd_dir: /lib/systemd/system
    master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
  roles:
    - { role: k3s/node }
